In [1]:
import pandas as pd

raw_df = pd.read_csv("updated_copy_num.csv")

In [2]:
raw_df

,Unnamed: 0,DepMap_ID,HNRNPA1P41,PRELID3BP1,BTNL12P,SMIM10L1,SNORD115-15,EGOT,MIPEPP2,RPL9P5,...,GPRIN2,EIF4E2,TTYH2,CD63,LPGAT1,EDEM1,TBC1D5,RPL23,GIT2,VPS9D1
0,0,ACH-000628,3.0,4.0,5.0,2.0,4.0,2.0,4.0,4.0,...,1.0,3.0,4.0,2.0,4.0,2.0,2.0,2.0,2.0,3.0
1,1,ACH-003071,3.0,2.0,2.0,2.0,2.0,2.0,2.0,3.0,...,1.0,3.0,2.0,3.0,2.0,2.0,2.0,3.0,3.0,2.0
2,2,ACH-001608,4.0,5.0,3.0,2.0,2.0,3.0,2.0,3.0,...,3.0,2.0,3.0,2.0,2.0,3.0,3.0,3.0,3.0,2.0
3,3,ACH-000278,1.0,2.0,2.0,2.0,2.0,1.0,2.0,1.0,...,1.0,2.0,2.0,2.0,2.0,1.0,2.0,1.0,2.0,1.0
4,4,ACH-001350,5.0,3.0,4.0,5.0,3.0,2.0,3.0,3.0,...,2.0,2.0,4.0,3.0,3.0,2.0,3.0,3.0,3.0,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1602,1602,ACH-001389,2.0,3.0,3.0,3.0,2.0,3.0,2.0,3.0,...,2.0,2.0,5.0,2.0,3.0,3.0,3.0,2.0,2.0,2.0
1603,1603,ACH-001835,2.0,4.0,4.0,3.0,3.0,2.0,5.0,2.0,...,6.0,4.0,4.0,3.0,4.0,2.0,2.0,4.0,3.0,3.0
1604,1604,ACH-000296,2.0,3.0,4.0,3.0,2.0,2.0,3.0,3.0,...,3.0,3.0,2.0,3.0,4.0,2.0,2.0,2.0,2.0,2.0
1605,1605,ACH-001971,2.0,4.0,3.0,4.0,4.0,3.0,4.0,4.0,...,3.0,4.0,3.0,4.0,4.0,4.0,4.0,4.0,4.0,3.0
1606,1606,ACH-002276,2.0,2.0,2.0,2.0,2.0,4.0,2.0,4.0,...,2.0,2.0,2.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0

In [13]:
cols = ['ModelID','StrippedCellLineName']
cells_df = pd.read_csv("Model.csv",usecols=cols)
cells_df.rename(columns={'ModelID':'DepMap_ID'},inplace=True)
cells_df

       DepMap_ID StrippedCellLineName
0     ACH-000001            NIHOVCAR3
1     ACH-000002                 HL60
2     ACH-000003                CACO2
3     ACH-000004                  HEL
4     ACH-000005              HEL9217
...          ...                  ...
2100  ACH-003473        CCLFPEDS0013T
2101  ACH-003474        CCLFHNSC0001T
2102  ACH-003475        CCLFHNSC0003T
2103  ACH-003476        CCLFHNSC0002T
2104  ACH-003480        CCLFTHYR0001T

[2105 rows x 2 columns]

In [23]:
merged_df = pd.merge(raw_df,cells_df,how='inner',on='DepMap_ID')
merged_df.insert(1,'cell_line',merged_df.pop('StrippedCellLineName'))
merged_df.drop(['Unnamed: 0','DepMap_ID'],axis=1,inplace=True)

In [31]:
cell_sort = merged_df.sort_index(axis=0)
cell_sort.set_index('cell_line',inplace=True)
cell_sort.sort_index(axis=1,inplace=True)
cell_sort

,A1BG,A1BG-AS1,A1CF,A2M,A2M-AS1,A2ML1,A2ML1-AS1,A2ML1-AS2,A2MP1,A3GALT2,...,ZWILCH,ZWINT,ZXDC,ZYG11A,ZYG11AP1,ZYG11B,ZYX,ZYXP1,ZZEF1,ZZZ3
cell_line,,,,,,,,,,,,,,,,,,,,,
NCIH596,4.0,4.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,3.0,...,4.0,2.0,5.0,3.0,3.0,3.0,2.0,4.0,3.0,3.0
NCIH748,4.0,4.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,...,2.0,2.0,2.0,3.0,3.0,3.0,3.0,3.0,4.0,3.0
NP2,2.0,2.0,4.0,2.0,2.0,2.0,2.0,2.0,2.0,6.0,...,2.0,4.0,3.0,4.0,2.0,4.0,3.0,2.0,2.0,4.0
COV362,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,...,2.0,2.0,2.0,2.0,2.0,2.0,3.0,4.0,1.0,2.0
HTCC3,3.0,3.0,3.0,5.0,5.0,5.0,5.0,5.0,5.0,3.0,...,3.0,3.0,4.0,4.0,4.0,4.0,2.0,7.0,2.0,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
SUM1315MO2,2.0,2.0,2.0,3.0,3.0,3.0,3.0,3.0,3.0,4.0,...,5.0,2.0,3.0,4.0,2.0,4.0,5.0,2.0,2.0,4.0
ICC106,5.0,5.0,6.0,3.0,3.0,3.0,3.0,3.0,3.0,2.0,...,3.0,6.0,4.0,4.0,2.0,4.0,2.0,3.0,2.0,4.0
OUMS23,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,...,2.0,3.0,4.0,3.0,3.0,3.0,2.0,3.0,1.0,3.0
MM466,3.0,3.0,3.0,4.0,4.0,4.0,4.0,4.0,4.0,3.0,...,4.0,3.0,3.0,3.0,2.0,3.0,7.0,4.0,3.0,3.0
MYM12,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,...,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0

In [32]:
cell_sort.reset_index(inplace=True)
cell_sort

,cell_line,A1BG,A1BG-AS1,A1CF,A2M,A2M-AS1,A2ML1,A2ML1-AS1,A2ML1-AS2,A2MP1,...,ZWILCH,ZWINT,ZXDC,ZYG11A,ZYG11AP1,ZYG11B,ZYX,ZYXP1,ZZEF1,ZZZ3
0,NCIH596,4.0,4.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,...,4.0,2.0,5.0,3.0,3.0,3.0,2.0,4.0,3.0,3.0
1,NCIH748,4.0,4.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,...,2.0,2.0,2.0,3.0,3.0,3.0,3.0,3.0,4.0,3.0
2,NP2,2.0,2.0,4.0,2.0,2.0,2.0,2.0,2.0,2.0,...,2.0,4.0,3.0,4.0,2.0,4.0,3.0,2.0,2.0,4.0
3,COV362,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,...,2.0,2.0,2.0,2.0,2.0,2.0,3.0,4.0,1.0,2.0
4,HTCC3,3.0,3.0,3.0,5.0,5.0,5.0,5.0,5.0,5.0,...,3.0,3.0,4.0,4.0,4.0,4.0,2.0,7.0,2.0,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1602,SUM1315MO2,2.0,2.0,2.0,3.0,3.0,3.0,3.0,3.0,3.0,...,5.0,2.0,3.0,4.0,2.0,4.0,5.0,2.0,2.0,4.0
1603,ICC106,5.0,5.0,6.0,3.0,3.0,3.0,3.0,3.0,3.0,...,3.0,6.0,4.0,4.0,2.0,4.0,2.0,3.0,2.0,4.0
1604,OUMS23,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,...,2.0,3.0,4.0,3.0,3.0,3.0,2.0,3.0,1.0,3.0
1605,MM466,3.0,3.0,3.0,4.0,4.0,4.0,4.0,4.0,4.0,...,4.0,3.0,3.0,3.0,2.0,3.0,7.0,4.0,3.0,3.0
1606,MYM12,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,...,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0

In [34]:
cell_sort.to_hdf('copy_number_data_041825.h5','copy_num')

In [36]:
test_df = pd.read_hdf('copy_number_data_041825.h5')
test_df

,cell_line,A1BG,A1BG-AS1,A1CF,A2M,A2M-AS1,A2ML1,A2ML1-AS1,A2ML1-AS2,A2MP1,...,ZWILCH,ZWINT,ZXDC,ZYG11A,ZYG11AP1,ZYG11B,ZYX,ZYXP1,ZZEF1,ZZZ3
0,NCIH596,4.0,4.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,...,4.0,2.0,5.0,3.0,3.0,3.0,2.0,4.0,3.0,3.0
1,NCIH748,4.0,4.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,...,2.0,2.0,2.0,3.0,3.0,3.0,3.0,3.0,4.0,3.0
2,NP2,2.0,2.0,4.0,2.0,2.0,2.0,2.0,2.0,2.0,...,2.0,4.0,3.0,4.0,2.0,4.0,3.0,2.0,2.0,4.0
3,COV362,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,...,2.0,2.0,2.0,2.0,2.0,2.0,3.0,4.0,1.0,2.0
4,HTCC3,3.0,3.0,3.0,5.0,5.0,5.0,5.0,5.0,5.0,...,3.0,3.0,4.0,4.0,4.0,4.0,2.0,7.0,2.0,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1602,SUM1315MO2,2.0,2.0,2.0,3.0,3.0,3.0,3.0,3.0,3.0,...,5.0,2.0,3.0,4.0,2.0,4.0,5.0,2.0,2.0,4.0
1603,ICC106,5.0,5.0,6.0,3.0,3.0,3.0,3.0,3.0,3.0,...,3.0,6.0,4.0,4.0,2.0,4.0,2.0,3.0,2.0,4.0
1604,OUMS23,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,...,2.0,3.0,4.0,3.0,3.0,3.0,2.0,3.0,1.0,3.0
1605,MM466,3.0,3.0,3.0,4.0,4.0,4.0,4.0,4.0,4.0,...,4.0,3.0,3.0,3.0,2.0,3.0,7.0,4.0,3.0,3.0
1606,MYM12,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,...,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0

In [37]:
curr_df = pd.read_hdf('copy_number_data.h5')
curr_df

,cell_line,A1BG,NAT2,ADA,CDH2,AKT3,ZBTB11-AS1,MED6,NR2E3,NAALAD2,...,HNRNPDL,DMTF1,PPP4R1,CDH1,SLC12A6,PTBP3,KCNE2,DGCR2,CASP8AP2,SCO2
0,1321N1,3.0,3.0,7.0,7.0,4.0,4.0,3.0,3.0,3.0,...,3.0,4.0,5.0,3.0,3.0,4.0,3.0,2.0,3.0,3.0
1,143B,3.0,3.0,5.0,3.0,3.0,4.0,5.0,5.0,3.0,...,3.0,3.0,5.0,4.0,4.0,3.0,3.0,3.0,3.0,3.0
2,22RV1,2.0,3.0,2.0,2.0,3.0,2.0,2.0,2.0,2.0,...,2.0,3.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0
3,2313287,2.0,2.0,4.0,2.0,2.0,3.0,2.0,2.0,2.0,...,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0
4,42MGBA,1.0,1.0,2.0,1.0,1.0,1.0,2.0,1.0,2.0,...,1.0,2.0,1.0,1.0,1.0,1.0,2.0,1.0,1.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
992,YH13,3.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,...,1.0,3.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0
993,YKG1,4.0,4.0,4.0,3.0,4.0,4.0,2.0,3.0,2.0,...,2.0,5.0,3.0,3.0,3.0,3.0,3.0,2.0,3.0,2.0
994,YMB1,3.0,3.0,4.0,4.0,7.0,3.0,3.0,4.0,2.0,...,4.0,5.0,4.0,6.0,4.0,3.0,2.0,5.0,4.0,2.0
995,ZR751,4.0,3.0,5.0,4.0,7.0,3.0,3.0,3.0,3.0,...,3.0,4.0,4.0,5.0,3.0,3.0,2.0,4.0,2.0,2.0
996,ZR7530,2.0,1.0,2.0,1.0,3.0,2.0,2.0,2.0,1.0,...,2.0,2.0,1.0,1.0,2.0,1.0,1.0,2.0,2.0,2.0

In [40]:
test_df.iloc['AKT1']

TypeError: Cannot index by location index with a non-integer key